SPI_model_S/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('core/', views.core, name="core"),
    path('controls/', views.controls, name="controls"),
    path('search/', views.search, name="search"),
    path('about/', views.about, name="about"),
    path('fine/',include("fine.urls")),
    path('suggestions/',include("suggestions.urls")),
    path('data-control/',include("dataControl.urls")),
    path('accounts/', include("accounts.urls")),
    path('announcements/',include("announcements.urls")),
    path('blog/',include("blog.urls")),
    path('catalog/',include("catalog.urls")),
    path('kiosk/',include("kiosk.urls")),
    path('transactions/',include("transactions.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),name="password_reset_complete"),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path('push/',views.blog_create,name="blog-create"),
    path('edit/<str:username>/<str:slug>/',views.blog_edit,name="blog-edit"),
    path('delete/<str:username>/<str:slug>/',views.blog_delete,name="blog-delete"),
    path('delete/confirm/<str:username>/<str:slug>/',views.blog_delete_confirm,name="blog-delete-confirm"),
    
]

catalog/urls.py
from django.urls import path
from . import views

app_name="catalog"

urlpatterns = [
    path('push/',views.book_create,name="book-create"),
    path('search/',views.book_search,name="book-search"),
    path('search-page/',views.book_searchpage,name="book-search-page"),
    path('trans-search/',views.book_trans_search,name="book-trans-search"),
    path('mtrans-search/',views.book_mtrans_search,name="book-mtrans-search"),
    path('edit/<int:booknumber>/',views.book_edit,name="book-edit"),
    path('delete/<int:booknumber>/',views.book_delete,name="book-delete"),
    path('delete/confirm/<int:booknumber>/',views.book_delete_confirm,name="book-delete-confirm"),
]

kiosk/urls.py
from django.urls import path
from . import views

app_name="kiosk"

urlpatterns = [
    path('',views.kiosk_home,name="kiosk-home"),
    path('opPicker/',views.kiosk_opPicker,name="kiosk-opPicker"),
    path('close/<reciept>',views.kioskClose,name="kiosk-Close"),
]

transactions/urls.py
from django.urls import path
from . import views

app_name="transactions"

urlpatterns = [
    path('manager/',views.transaction_manager,name="transaction-manager"),
    path('manager/kiosk/',views.transaction_manager_kiosk,name="transaction-manager-kiosk"),
    path('ajax/trans-stack/',views.transaction_stack,name="transaction-stack"),
    path('ajax/trans-stack-kiosk/',views.transaction_stack_kiosk,name="transaction-stack-kiosk"),
    path('ajax/admin-trans-search/',views.admin_trans_search,name="admin-trans-search"),
    path('ajax/admin-user-search/',views.admin_user_search,name="admin-user-search"),
    path('addStack/',views.transactionStackAdd,name="transaction-stack-add"),
    path('delStack/',views.transactionStackDelete,name="transaction-stack-delete"),
    path('transaction-filters/',views.transactionFilters,name="transaction-filters"),
    path('charts/gender/',views.chartsView,name="transactions-gender-chart"),
]

kiosk/models.py
from django.db import models

# Create your models here.

kiosk/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import login,logout
from accounts.models import User
from transactions.models import Transaction,TransactionStack

def kiosk_home(request):
	if(request.user.is_authenticated):
		user=request.user
		TransactionStack.objects.filter(user=user).delete()
		logout(request)
	return render(request,'kiosk/kiosk_home.html')

def kiosk_opPicker(request):
	if(request.method=='POST'):
		userBarcode=request.POST['userBarcode']
		userPin=request.POST['userPin']
		if(User.objects.filter(barcode=userBarcode).exists()):
			user=User.objects.get(barcode=userBarcode)
			if(user.pin==userPin):
				login(request,user)
				return render(request,'kiosk/kiosk_opPicker.html')
			else:
				messages.success(request,f'Incorrect PIN!')

		else:
			messages.success(request,f'Invalid User !')

	else:
		messages.success(request,f'Request Error - Action undefined !')

	return redirect('/kiosk')

def kioskClose(request,reciept):
	return render(request,"kiosk/kioskClose.html",{'reciept':reciept})

kiosk/templates/kiosk/SPIMail.html
<html>
<body>
</body>
</html>

kiosk/templates/kiosk/kioskClose.html
{% extends 'subBase2.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

		<style>
			.kioskClose{
				height: 600px;
				overflow-y:scroll;
			}
			</style>

            <h1>Process Close</h1>
            <hr>
            	<div class="row kioskClose">
					
					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
						{{reciept}}
						<button class="btn btn-success">New transaction</button>
		          	</div>


			
				</div>
        {% endblock %}

kiosk/templates/kiosk/kioskPrint.html
<html>
<head>
</head>
<body>
  <h1>Transaction Record</h1>
  <p>{{date}}</p>
  <p>{{college}}</p>
  <p>{{transType}}</p>
  ---------------------------
  <br>{{user}}
  <ol>
  {%for book in books%}
      <li>{{book.book_number}} - {{book.book_title}}</li>
  {% endfor %}
  </ol>
</body>
</html>

kiosk/templates/kiosk/kiosk_home.html
{% extends 'subBase2.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

		<style>
			.barcode{
				height: 600px;
				overflow-y:scroll;
			}
			</style>

            <h1>Kiosk Login</h1>
            <hr>
            <div class="container">
            	<div class="row barcode">

					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
						<br>
						<form method="POST" action="{% url 'kiosk:kiosk-opPicker' %}">
					    	<center>

						    	{% csrf_token %}
					           	<input class="form-control" type="text" id="userBarcode" type="text" name="userBarcode" placeholder="Enter User Barcode" autofocus="true">
					           	<br><input class="form-control" type="password" id="userPin" name="userPin" style="display:none;" placeholder="Enter PIN">
					           	<br><input type="submit" class="btn btn-success"  value="Login">
					

		            		</center>
		            	</form>
		          	</div>
				</div>
			</div>
        {% endblock %}

        {% block script %}
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script type="text/javascript">
        $("#userBarcode").change(function () {
      		var userBarcode=$(this).val();
      		if(userBarcode.length!=0){
      			$("#userPin").css("display", "block");
      		}
      	})
      	</script>
    	{% endblock %}

kiosk/templates/kiosk/kiosk_opPicker.html
{% extends 'subBase2.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

		<style>
			.kiosk-board{
				height: 680px;
				overflow-y:scroll;
			}
		</style>
		<div class="container kiosk-board">
			<img src="{{request.user.profile.image.url}}" style="max-height: 50px;max-width:50px;" class="img-rounded">
			<h3>Hello,{{request.user}}</h3>
			<a href="/kiosk/"><button class="btn btn-danger">Logout</button></a>
			<hr>
			<form class="form-inline" method="POST" action="{% url 'transactions:transaction-manager-kiosk' %}">
				{% csrf_token %}
				<input type="hidden" name="user" id="user" value={{request.user}}>
			    <input class="btn btn-success" name="issue" type="submit" value="Create Transaction">
			    <input class="btn btn-primary ml-1 ml-sm-1 ml-md-0 ml-lg-2 ml-xl-2" name="return" type="submit" value="Make Return">
	        </form>
	        <br>
	        <br>
		    <form class="form-inline" method="GET">
			    <input class="form-control" id="transquery" type="text" name="query" placeholder="Search Book" autofocus>
			        &nbsp;&nbsp;&nbsp;<input type="checkbox" id="nobarcode" onclick="validate()">&nbsp;Barcode Error?
			        &nbsp;&nbsp;&nbsp;<input class="form-control" id="mquery" type="text" name="mquery"  style="display: none;" placeholder="Use if barcode fails">
	            </form>
	            <br>
	            <p class="text-justify" id="messagedump"></p>
	            <div id="mqueryjsondump"></div>
	            <br><br>
	            <h2>Current Transaction Queue</h2>
	            <hr>
	            <div class="row">
					<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
						<b>Number</b>
					</div>
					<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
						<b>Title</b>
					</div>
					<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
						<b>Author</b>
					</div>
					<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
						<b>Category</b>
					</div>
				</div>
				<hr>
				<p class="text-justify" id="transStackdump"></p>
				<br><br>
		</div>
		{% endblock %}

		{% block script %}
		<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
		<script src="https://code.highcharts.com/highcharts.src.js"></script>
		<script>
			$("#transquery").keyup(function () {
      			var transquery=$(this).val();
      			if(transquery.length!=0){
	      			$.ajax({
				        url: "{% url 'transactions:transaction-stack-add' %}",
				        data: {
				          'book_number': transquery
				        },
				        success: StackSuccess,
				        dataType: 'html'
	      			});
	      		}
	      		else{
      				$('#messagedump').html("<b>Keep Looking or Complete the Transaction !</b>");
      			}
    		});

    		$("#mquery").keyup(function () {
      			var mquery=$(this).val();
      			if(mquery.length!=0 || mquery!=''){
	      			$.ajax({
				        url: "{% url 'catalog:book-mtrans-search' %}",
				        data: {
				          'mquery': mquery
				        },
				        success: mquerySuccess,
				        dataType: 'html'
	      			});
	      			 $('#messagedump').html("");
	      		}
	      		else{
      				$('#messagedump').html("<b>Keep Looking or Complete the Transaction !</b>");
      				$('#mqueryjsondump').html("");
      			}
    		});

    		function mquerySuccess(data,textStatus,jqXHR){
    			$('#mqueryjsondump').html(data);
    		}

    		function AddtoStack(book_number){
    			$.ajax({
    				url:"{% url 'transactions:transaction-stack-add' %}",
    				dataType:'html',
    				data: {
    					'book_number': book_number
    				},
    				success: StackSuccess
    			});
    		}

    		function RemoveFromStack(book_number){
    			$.ajax({
    				url:"{% url 'transactions:transaction-stack-delete' %}",
    				dataType:'html',
    				data: {
    					'book_number': book_number
    				},
    				success: StackSuccess
    			});
    		}

    		function StackSuccess(data,textStatus,jqXHR)
    		{
    			$('#messagedump').html(data);
    			TransactionStackAjax();
    			clearForm();
    		}

    		function clearForm(){
    			document.getElementById("transquery").value="";
    			document.getElementById("mquery").value="";
    			document.getElementById("mqueryjsondump").innerHTML="";
    		}

    		function TransactionStackAjax(){
            	$.ajax({
    				url:"{% url 'transactions:transaction-stack-kiosk' %}",
    				dataType:'html',
    				success: TransStackSuccess
    			});
        	}

    		function TransStackSuccess(data,textStatus,jqXHR)
    		{
    			$('#transStackdump').html(data);
    		}

    		function validate() {
        		if (document.getElementById('nobarcode').checked) {
            		document.getElementById('mquery').style.display="block";
        		}
        		else {
            		document.getElementById('mquery').style.display="none";
            	}
    		}

    		$(document).ready(TransactionStackAjax());

    	</script>

		{% endblock %}