SPI_model_S/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('core/', views.core, name="core"),
    path('controls/', views.controls, name="controls"),
    path('search/', views.search, name="search"),
    path('about/', views.about, name="about"),
    path('fine/',include("fine.urls")),
    path('suggestions/',include("suggestions.urls")),
    path('data-control/',include("dataControl.urls")),
    path('accounts/', include("accounts.urls")),
    path('announcements/',include("announcements.urls")),
    path('blog/',include("blog.urls")),
    path('catalog/',include("catalog.urls")),
    path('kiosk/',include("kiosk.urls")),
    path('transactions/',include("transactions.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),name="password_reset_complete"),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

announcements/urls.py
from django.urls import path
from . import views

app_name="announcements"

urlpatterns = [
    path('push/',views.announcement_create,name="announcements-create"),
    path('edit/<str:slug>/',views.announcement_edit,name="announcements-edit"),
    path('delete/<str:slug>/',views.announcement_delete,name="announcements-delete"),
    path('delete/confirm/<str:slug>/',views.announcement_delete_confirm,name="announcements-delete-confirm"),
]

blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path('push/',views.blog_create,name="blog-create"),
    path('edit/<str:username>/<str:slug>/',views.blog_edit,name="blog-edit"),
    path('delete/<str:username>/<str:slug>/',views.blog_delete,name="blog-delete"),
    path('delete/confirm/<str:username>/<str:slug>/',views.blog_delete_confirm,name="blog-delete-confirm"),
    
]

announcements/models.py
from django.db import models

class Announcement(models.Model):
	content=models.TextField()
	date_posted=models.DateField(auto_now_add=True)
	attachments=models.FileField(blank=True,upload_to="announcements")
	slug=models.SlugField(unique=True)

	def __str__(self):
		return str(self.content)+" | "+str(self.date_posted)

announcements/forms.py
from django import forms 
from .models import Announcement

class AnnouncementForm(forms.ModelForm):
	class Meta:
		model=Announcement
		fields=['content','attachments']
		

announcements/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required,user_passes_test
from accounts.models import User
from .models import Announcement
from .forms import AnnouncementForm

@user_passes_test(lambda u: u.is_staff)
def announcement_create(request):
	if(request.method=='POST'):
		announcementForm=AnnouncementForm(request.POST,request.FILES)
		if(announcementForm.is_valid()):
			instance=announcementForm.save(commit=False)
			count=Announcement.objects.all().count()
			instance.slug="announcement-"+str(count)+"-"+str(instance.content)
			instance.save()
			messages.success(request,f'Announcement Posted !')
			return redirect('/controls/')
		
		messages.success(request,f'Validation error - Explicit or invalid data format !')
		
	else:
		announcementForm=AnnouncementForm()

	return render(request,'announcements/announcement_create.html',{'announcementForm':announcementForm})

@user_passes_test(lambda u: u.is_staff)
def announcement_edit(request,slug):
	announcement=Announcement.objects.get(slug=slug)
	if(request.method=='POST'):
		announcementEditForm=AnnouncementForm(request.POST,request.FILES,instance=announcement)
		if(announcementEditForm.is_valid()):
			announcementEditForm.save()
			messages.success(request,f'Announcement Updated !')
			return redirect("/controls/")

		messages.success(request,f'Validation error - Explicit or invalid data format !')
		return redirect('/controls/')
		
	else:
		editForm=AnnouncementForm(instance=announcement)
		return render(request,"announcements/announcement_edit.html",{'announcement':announcement,'editForm':editForm})

@user_passes_test(lambda u: u.is_staff)	
def announcement_delete_confirm(request,slug):
	if(request.method=='POST'):
		announcement=Announcement.objects.get(slug=slug)
		return render(request,"announcements/announcement_delete_confirm.html",{'announcement':announcement})
	
	else:
		messages.success(request,f'Request Error - Undefined Action !')
		return redirect('/controls/')

@user_passes_test(lambda u: u.is_staff)
def announcement_delete(request,slug):
	if(request.method=='POST'):
		Announcement.objects.get(slug=slug).delete()
		messages.success(request,f'Announcement deleted !')
		return redirect("/controls/")
		
	else:
		messages.success(request,f'Request Error - Undefined Action !')
		return redirect('/controls/')		

announcements/templates/announcements/announcement_create.html
{% extends 'base.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<style>
			.card{
				height: 700px;
				overflow-y: scroll;
			}
			</style>	
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<legend>Create</legend>
							</div>
							<div class="card-body">
								<form method="POST" action="{% url 'announcements:announcements-create' %}" enctype="multipart/form-data">
									{% csrf_token %}
									{{announcementForm|crispy}}
									<div class="form-group">
										<button class="btn btn-success" type="submit">
											Post
										</button>
									</div>
								</form>
								<a href="/controls/" class="btn btn-info">Cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock %}

announcements/templates/announcements/announcement_delete_confirm.html
{% extends 'base.html' %}
	{% load staticfiles %}
		{% block content %}
			<style>
				.card{
					height: 700px;
					overflow-y: scroll;
				}
			</style>	
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<legend>Delete Announcement</legend>
							</div>
							<div class="card-body">
								<h2 class="text-justify">Are you sure you want to delete the Announcement - "{{announcement.content}}" ? This cannot be undone</h2>
								<hr>
								<form method="POST" action="{% url 'announcements:announcements-delete' announcement.slug %}" class="form-group">
									{% csrf_token %}
									<input type="submit" class="btn btn-danger" value="Delete">
								</form>
								<a class="btn btn-primary" href="/controls/">Cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock %}

announcements/templates/announcements/announcement_edit.html
{% extends 'base.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<style>
			.card{
				height: 700px;
				overflow-y: scroll;
			}
			</style>	
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<legend>Edit</legend>
							</div>
							<div class="card-body">
								<form method="POST" action="{% url 'announcements:announcements-edit' announcement.slug %} " class="form-group" enctype="multipart/form-data">
									{% csrf_token %}
									{{editForm|crispy}}
									<input type="submit" class="btn btn-success" value="Update">
								</form>
								<a class="btn btn-primary" href="/controls/">Cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock %}