SPI_model_S/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('core/', views.core, name="core"),
    path('controls/', views.controls, name="controls"),
    path('search/', views.search, name="search"),
    path('about/', views.about, name="about"),
    path('fine/',include("fine.urls")),
    path('suggestions/',include("suggestions.urls")),
    path('data-control/',include("dataControl.urls")),
    path('accounts/', include("accounts.urls")),
    path('announcements/',include("announcements.urls")),
    path('blog/',include("blog.urls")),
    path('catalog/',include("catalog.urls")),
    path('kiosk/',include("kiosk.urls")),
    path('transactions/',include("transactions.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),name="password_reset_complete"),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('login/',views.login_view,name="accounts-login"),
    path('logout/',views.logout_view,name="accounts-logout"),
    path('profile/',views.profile,name="accounts-profile"),
    path('setup/',views.setup,name="accounts-setup"),
]

blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path('push/',views.blog_create,name="blog-create"),
    path('edit/<str:username>/<str:slug>/',views.blog_edit,name="blog-edit"),
    path('delete/<str:username>/<str:slug>/',views.blog_delete,name="blog-delete"),
    path('delete/confirm/<str:username>/<str:slug>/',views.blog_delete_confirm,name="blog-delete-confirm"),
    
]

catalog/urls.py
from django.urls import path
from . import views

app_name="catalog"

urlpatterns = [
    path('push/',views.book_create,name="book-create"),
    path('search/',views.book_search,name="book-search"),
    path('search-page/',views.book_searchpage,name="book-search-page"),
    path('trans-search/',views.book_trans_search,name="book-trans-search"),
    path('mtrans-search/',views.book_mtrans_search,name="book-mtrans-search"),
    path('edit/<int:booknumber>/',views.book_edit,name="book-edit"),
    path('delete/<int:booknumber>/',views.book_delete,name="book-delete"),
    path('delete/confirm/<int:booknumber>/',views.book_delete_confirm,name="book-delete-confirm"),
]

suggestions/urls.py
from django.urls import path
from . import views

app_name="suggestions"

urlpatterns = [
    path('push/',views.suggestion_create,name="suggestions-create"),
]

templates/about.html
{% extends 'subBase2.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<div class="row">
				<div class="col-xl-7 col-lg-7 col-md-7 col-sm-12 col-12">
				    <div class="card">
						<div class="card-header"><h2>Library Stats</h2></div>
						<div class="card-body">
							<div class="row">
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
									<center><img src="{% static 'images/books.png' %}" class="img-responsive" style="height:60px;width: 60px;" /></center>
									<center><h1>1,26,445</h1></center>
									<center><h2>No of books in library</h2></center>
								</div>
								<br><br>
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
								    <center><img src="{% static 'images/ebook.png' %}" class="img-responsive" style="height:60px;width: 60px;" /></center>
								    <center><h1>10</h1></center>
                                    <center><h2>No of E-books in library</h2></center>
								</div>
								<br><br>
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
									<center><img src="{% static 'images/report.png' %}" class="img-responsive" style="height:60px;width: 60px;" /><br></center>
								    <center><h1>267</h1></center>
									<center><h2>No of Journals</h2></center>
								</div>
							</div>
							<hr>
							<div class="row">
								<br>
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
									<center><img src="{% static 'images/seo.png' %}" class="img-responsive" style="height:60px;width: 60px;" /><br></center>
								    <center><h1>9936</h1></center>
									<center><h2>No of E-Journals</h2></center>
								</div>
								<br><br>
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
								    <center><img src="{% static 'images/magazine.png' %}" class="img-responsive" style="height:60px;width: 60px;" /><br></center>
								    <center><h1>36</h1></center>
									<center><h2>No of Magazines</h2></center>
								</div>
								<br><br>
								<div class="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-12">
								    <center><img src="{% static 'images/students.png' %}" class="img-responsive" style="height:60px;width: 60px;" /><br></center>
								    <center><h1>5000+</h1></center>
									<center><h2>No of Students registered</h2></center>
								</div>
							</div>
							<hr>
							<center><h2>Gender Ratio</h2></center>
							<br>
							<div class="row">
								<div class="col-xl-6 col-lg-6 col-md-12 col-sm-6 col-6">
									<center>
										<img src="{% static 'images/male.png' %}" class="img-responsive" style="max-height:60px;max-width: 60px;" /><br>
										<h1 class="Count">{{male_count}}</h1>
									</center>
								</div>
								<br>
								<div class="col-xl-6 col-lg-6 col-md-12 col-sm-6 col-6">
									<center>
										<img src="{% static 'images/female.png' %}" class="img-responsive" style="max-height:60px;max-width: 60px;" /><br>
										<h1 class="Count">{{female_count}}</h1>
									</center>
								</div>
							</div>
							<hr>
						</div>
					</div>
				</div>
				<br>
			    <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12 col-12">
			        <div class="card">
						<div class="card-header">
							<h2>Library Layout Map</h2>
						</div>
						<div class="card-body">
						   	<a href="{% static 'images/library_final-1.jpg' %}" target="_blank"><img src="{% static 'images/library_final-1.jpg' %}" class="img-thumbnail" style="height:690px;width:auto;" /></a>
						</div>
					</div>
			    </div>
		    </div>

		{% endblock %}

templates/additions.html
<html>
	<body>
		<h1>SPI-Library Management System</h1>
		<br><br>
		<h4>New bulk addition request</h4><hr>
		<h2>{{college}}</h2>
		<br>
		<h4>for data model</h4>
		<h2>{{data_model}}</h2>
		<hr>
		<br>
	</body>
</html>

templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
	<head>
		<!-- Meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!--Bootstrap-->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

		<!-- Font Awesome JS -->
		<script src="https://use.fontawesome.com/7171492551.js"></script>

		<!--Title-->
		<title>SPI - Library Management Engine</title>
	</head>

	<style type="text/css">
        .loader {
            border: 16px solid #f3f3f3;
            border-radius: 50%;
            border-top: 16px solid #3498db;
            width: 120px;
            height: 120px;
            -webkit-animation: spin 2s linear infinite; /* Safari */
            animation: spin 2s linear infinite;
          }

          /* Safari */
          @-webkit-keyframes spin {
            0% { -webkit-transform: rotate(0deg); }
            100% { -webkit-transform: rotate(360deg); }
          }

          @keyframes spin {
            0% { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
          }

		.nav-tabs .nav-link.active {
	    	font-weight:bold;
	    	background-color: transparent;
	    	border-bottom:3px solid #dd0000;
	    	border-right: none;
	    	border-left: none;
	    	border-top: none;
		}

		a:hover{
			text-decoration: none;
		}

		.article-title {
		  color: #444444;
		}

		a.article-title:hover {
		  color: #428bca;
		  text-decoration: none;
		}

		.article-content {
		  white-space: pre-line;
		}

		.article-img {
		  height: 65px;
		  width: 65px;
		  margin-right: 16px;
		}

		.article-metadata {
		  padding-bottom: 1px;
		  margin-bottom: 4px;
		  border-bottom: 1px solid #e3e3e3
		}

		.article-metadata a:hover {
		  color: #333;
		  text-decoration: none;
		}

		.article-svg {
		  width: 25px;
		  height: 25px;
		  vertical-align: middle;
		}

		.account-img {
		  height: 125px;
		  width: 125px;
		  margin-right: 20px;
		  margin-bottom: 16px;
		  size: cover;
		}

		.account-heading {
		  font-size: 2.5rem;
		}


	</style>

	<body style="overflow-x: hidden;background: #fafafa;height: 100%;width: 100%;">

		<!--Navbar-->
		<nav class="navbar navbar-expand-lg navbar-light bg-white" style="background-color: white !important;
  			box-shadow: 0 4px 2px -2px rgba(128,0,0);">
	        <div class="container-fluid">
	        	<!--<a href="http://www.griet.ac.in/" target="_blank">
	            	<img src="{% static 'images/GRIET_Logo.png' %}" class="img-responsive" style="max-width: 390px;max-height: 390px;">
	        	</a>-->
	        	<h1>College Name</h1>
	        </div>
  			<!-- Navbar links -->
  			<div class="collapse navbar-collapse" id="collapsibleNavbar">
    			<ul class="navbar-nav">
     	 			<li class="nav-item">
        				<a class="nav-link" href="/core/">Home</a>
      				</li>
      				<li class="nav-item">
        				<a class="nav-link" href="/search/">Search</a>
      				</li>
      				<li class="nav-item">
        				<a class="nav-link" href="#">Help</a>
      				</li>
      				<li class="nav-item">
        				<a class="nav-link" href="#">Support</a>
      				</li>
    			</ul>
  			</div>
	        <div class="container-fluid">
	        	<!-- Toggler/collapsibe Button -->
  			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
   	 			<span class="navbar-toggler-icon"></span>
  			</button>
	        	<div class="nav navbar-nav ml-auto">
	     			<li class="nav-item dropdown">
			            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			                <img class="rounded-circle article-img" src="{{request.user.profile.image.url}}">
			            </a>
			           	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
			           		<p style="margin:2px 10px;">Hello, {{request.user.username}}</p>
			                <div class="dropdown-divider"></div>
			                <a class="dropdown-item" href="/controls/">Dashboard</a>
			                <div class="dropdown-divider"></div>
			                <a class="dropdown-item" href="{% url 'accounts:accounts-logout' %}">Logout</a>
			            </div>
			        </li>
	        	</div>
	        </div>
        </nav>

        <br>
        <!--content-->
        <div class="container-fluid" style="margin-bottom: 20px;">
		        <div class="md-8">
		        	{{authForm}}
		        {% if messages %}
				    {% for message in messages %}
				    	<div class="alert alert-{{message.tags}}">
				    		{{message}}
				    	</div>
				    	<br><br>
				    {% endfor %}
				{% endif %}
				</div>
			{% block content %}{% endblock %}
		</div>

        <!--Footer-->
        <div class="footer">
			<div class="row flex align-items-center" style="background-color: #FFF8DC;">

		    	<!-- Grid column -->
		      	<div class="col-md-7 col-lg-8 d-none d-md-block">
		      		<a href="#">
		      			<img src="#" class="img-responsive" style="max-width: 150px;max-height: 150px;" />
		      		</a>
		      	</div>

		      	<div class="col-sm-12 col-12 d-md-none">
		      			<center>
		      				<a href="#">
		      					<img src="#" class="img-responsive" style="max-width: 150px;max-height: 150px;" />
		      				</a>
		      			</center>
		      	</div>

		      	<!-- Grid column -->
		      	<div class="col-md-5 col-lg-4 ml-lg-0">
		      		<br>
		        	<!-- Social buttons -->
		        	<div class="text-center text-md-right">
		          		<ul class="list-unstyled list-inline">
			           		<li class="list-inline-item">
			              		<a class="mx-3" href="#">
			                		<i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
			              		</a>
			            	</li>
			            	<li class="list-inline-item">
			              		<a class="mx-3" href="#">
			                		<i class="fa fa-twitter fa-2x"></i>
			              		</a>
			            	</li>
			            	<li class="list-inline-item">
			              		<a class="mx-3" href="#">
			                		<i class="fa fa-google-plus fa-2x"></i>
			              		</a>
			            	</li>
			            	<li class="list-inline-item">
			              		<a class="mx-3" href="#">
			                		<i class="fa fa-linkedin fa-2x"></i>
			              		</a>
			            	</li>
		          		</ul>
		        	</div>

		      	</div>

		      	<div class="col-md-12">
		      		<hr style="display: block; height: 1px;border: 0; border-top: 1px solid grey;margin: 1em 45em; padding: 0;">
		      		<center><small>© Developed by <a href="https://www.owlstack.in">OwlStack | Outsourcing</a><br></small></center><br>
		      	</div>
			</div>
		</div>
		{% block script %}{% endblock %}
	</body>
</html>

templates/controls.html
{% extends 'base.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<style>
			.card{
				height: 600px;
				overflow-y: scroll;
			}
			</style>	

			<div class="row">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
					<nav class="nav-justified" id="tabsNav">
		                <div class="nav nav-tabs " id="nav-tab" role="tablist">
		                    <a class="nav-item nav-link active" id="pop1-tab" data-toggle="tab" href="#pop1" role="tab" aria-controls="pop1" aria-selected="true"><i class="fa fa-user fa-2x" aria-hidden="true"></i><br>Profile</a>
		                    <a class="nav-item nav-link" id="pop2-tab" data-toggle="tab" href="#pop2" role="tab" aria-controls="pop2" aria-selected="false"><i class="fa fa-rss fa-2x" aria-hidden="true"></i><br>Your Blog Posts</a>
		                    <a class="nav-item nav-link" id="pop3-tab" data-toggle="tab" href="#pop3" role="tab" aria-controls="pop3" aria-selected="false"><i class="fa fa-commenting fa-2x" aria-hidden="true"></i><br>Suggestions</a>
		                </div>
		            </nav>
		            <div class="card">
						<div class="card-body">
		                	<div class="tab-content" id="nav-tabContent">
		                  		<div class="tab-pane fade show active" id="pop1" role="tabpanel" aria-labelledby="pop1-tab">
		                        	<div class="pt-3"></div>
		                        	<div class="media">
		   								<img class="rounded-circle account-img" src="{{user.profile.image.url}}">
		    							<div class="media-body">
		      								<h3>{{user.username}}</h3>
		      								<small>{{user.email}}</small>
		      								<br>
		      								<small>{{user.branch}}</small>
		      								<br>
		      								<small>{{user.gender}}</small>
		      								<br><br>
		      								<a href="/password-reset/">Reset Password</a>
		      								<br><br>
		      								<p class="text-secondary text-justify">{{user.profile.bio}}</p>	
		    							</div>
									</div>
									<hr>
		                        	<form method="POST" action="{% url 'accounts:accounts-profile' %}" enctype="multipart/form-data">
										{% csrf_token %}
										<fieldset class="form-group">
											<legend class="bordor-bottom mb-4">Update Profile</legend>
											{{profileForm|crispy}}
										</fieldset>
										<div class="form-group">
											<button class="btn btn-outline-info" type="submit">
												Update
											</button>
										</div>
									</form>
		                      	</div>
		                  		<div class="tab-pane fade" id="pop2" role="tabpanel" aria-labelledby="pop2-tab">
		                       		<div class="pt-3"></div>
									<h2>Your Posts - {{posts.count}}</h2>
									<br>
		                        	{% for post in posts %}
		                        		<article class="media">
											<img class="rounded-circle article-img" src="{{post.author.profile.image.url}}">
  											<div class="media-body">
			    								<div class="article-metadata">
			      									<a class="mr-2" href="#">{{ post.author }}</a>
			      									<small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
			    								</div>
			    								<h2>{{ post.title }}</h2>
			    									&nbsp;<a href="{% url 'blog:blog-edit' request.user post.slug %}" class="btn btn-warning btn-sm mt-1 mb-1">Edit</a>
				    								<form class="form-group" style="float: left;" action="{% url 'blog:blog-delete-confirm' request.user.username post.slug %}" method="POST">
			    									{% csrf_token %}
			    									<input class="btn btn-danger btn-sm mt-1 mb-1" type="submit" value="Delete">
			    								</form>
			    								<hr>
			    								<p class="article-content text-justify">{{ post.content }}</p>
			    								{% if post.thumbnail %}
			    									<img src="{{post.thumbnail.url}}" style="max-height: 300px;max-width: 300px;">
			    								{% endif %}
											</div>
										</article>
										<br><br>
									{% endfor %}
		                      	</div>
		                  		<div class="tab-pane fade" id="pop3" role="tabpanel" aria-labelledby="pop3-tab">
		                       		<div class="pt-3"></div>
		                        	<form method="POST" action="{% url 'suggestions:suggestions-create' %}">
										{% csrf_token %}
										<fieldset class="form-group">
											<legend class="bordor-bottom mb-4">Feedback</legend>
											<p class="text-muted">We appreciate your effort and time to pass us improvements to be better. Please be polite and constructive while pushing a suggestion. Your User information is not stored. All the suggestions are completely anonymous and not visible to anyone else other than the admin.
											{{suggForm|crispy}}
										</fieldset>
										<div class="form-group">
											<button class="btn btn-outline-info" type="submit">
												Send
											</button>
										</div>
									</form>
		                      	</div>
		                	</div>
	                	</div>
                	</div>
				</div>
			</div>	
		{% endblock %}

templates/search.html
{% extends 'subBase2.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<style>
			.search{
				height: 600px;
				overflow-y:scroll;
			}
			</style>

            <h1>Search</h1>
            <hr>

			<div class="row search">
				<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
				    <form class="form-inline" method="GET">
			           	<input class="form-control" id="query" type="text" name="query" placeholder="Search Book">
	            	</form>
	            	<hr>
	                <center>
						<div id="load" style="display: none" class="loader"></div>
					</center>
					<p class="text-justify" id="jsondump"></p>
				</div>
			</div>

        {% endblock %}

        {% block script %}
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script>
			    $("#query").keyup(function () {
      			var query=$(this).val();
      			if(query.length!=0){
      			    $("#load").css("display", "block");
      			    $("#jsondump").css("display", "none")
	      			$.ajax({
				        url: "{% url 'catalog:book-search-page' %}",
				        data: {
				          'query': query
				        },
				        success: searchSuccess,
				        dataType: 'html'
	      			});
      			}
      			else{
      			    $("#load").css("display", "none");
      			    $("#jsondump").css("display", "block");
      				$('#jsondump').html("<b>Keep Looking!</b>");
      			}
    		});

    		function searchSuccess(data,textStatus,jqXHR)
    		{
    		    $("#load").css("display", "none");
    		    $("#jsondump").css("display", "block");
    			$('#jsondump').html(data);
    		}
		</script>
		{% endblock %}