SPI_model_S/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('core/', views.core, name="core"),
    path('controls/', views.controls, name="controls"),
    path('search/', views.search, name="search"),
    path('about/', views.about, name="about"),
    path('fine/',include("fine.urls")),
    path('suggestions/',include("suggestions.urls")),
    path('data-control/',include("dataControl.urls")),
    path('accounts/', include("accounts.urls")),
    path('announcements/',include("announcements.urls")),
    path('blog/',include("blog.urls")),
    path('catalog/',include("catalog.urls")),
    path('kiosk/',include("kiosk.urls")),
    path('transactions/',include("transactions.urls")),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_done.html"),name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"),name="password_reset_confirm"),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),name="password_reset_complete"),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns = [
    path('push/',views.blog_create,name="blog-create"),
    path('edit/<str:username>/<str:slug>/',views.blog_edit,name="blog-edit"),
    path('delete/<str:username>/<str:slug>/',views.blog_delete,name="blog-delete"),
    path('delete/confirm/<str:username>/<str:slug>/',views.blog_delete_confirm,name="blog-delete-confirm"),
    
]

catalog/urls.py
from django.urls import path
from . import views

app_name="catalog"

urlpatterns = [
    path('push/',views.book_create,name="book-create"),
    path('search/',views.book_search,name="book-search"),
    path('search-page/',views.book_searchpage,name="book-search-page"),
    path('trans-search/',views.book_trans_search,name="book-trans-search"),
    path('mtrans-search/',views.book_mtrans_search,name="book-mtrans-search"),
    path('edit/<int:booknumber>/',views.book_edit,name="book-edit"),
    path('delete/<int:booknumber>/',views.book_delete,name="book-delete"),
    path('delete/confirm/<int:booknumber>/',views.book_delete_confirm,name="book-delete-confirm"),
]

catalog/models.py
from django.db import models
from accounts.models import User
from django.urls import reverse

TYPE_CHOICES = (
    ('E-Book Only','E-Book Only'),
    ('Hard Cover Only', 'Hard Cover Only'),
    ('Both Hard Cover and E-Book','Both Hard Cover and E-Book'),
)

class Book(models.Model):

	book_number=models.PositiveIntegerField(default=1,unique=True)
	book_title=models.CharField(max_length=30)
	book_author=models.CharField(max_length=30,default="No Info",blank=True,null=True)
	book_author2=models.CharField(max_length=30,default="No Info",blank=True,null=True)
	book_publisher=models.CharField(max_length=30,default="Information not available")
	book_category=models.CharField(max_length=30,null=True,blank=True)
	book_cost=models.PositiveIntegerField(default=0)
	book_language=models.CharField(max_length=30,default="ENG-US")
	book_type=models.CharField(max_length=26,choices=TYPE_CHOICES,default='Hard Cover Only')
	ebook_attachments=models.FileField(blank=True,upload_to="catalog/ebooks")
	book_quantity=models.PositiveIntegerField(default=100)
	book_shelf=models.CharField(max_length=10,default="1A")
	book_date_added=models.DateField(auto_now_add=True)

	def __str__(self):
		return str(self.book_number)

catalog/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
	class Meta:
		model=Book
		exclude=('book_date_added',)

class SearchForm(forms.Form):
	query=forms.CharField(max_length=100)
	def __init__(self, *args, **kwargs):
		super(SearchForm, self).__init__(*args, **kwargs)
		self.fields['query'].widget.attrs['placeholder'] = self.fields['query'].label or 'Search Book'
		self.fields['query'].help_text = None
		self.fields['query'].label = False
			

catalog/views.py
from django.shortcuts import render_to_response,render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Book
from .forms import BookForm

@login_required(login_url="accounts:accounts-login")
def book_search(request):
	query=request.GET.get('query',None)
	books=Book.objects.filter(Q(book_title__contains=query) | Q(book_author__contains=query) | Q(book_category__contains=query) | Q(book_number__contains=query))
	result=True
	user=request.user
	return render_to_response('catalog/ajax_search.html',{'books':books[:20],'result':result,'user':user})

def book_searchpage(request):
	query=request.GET.get('query',None)
	books=Book.objects.filter(Q(book_title__contains=query) | Q(book_author__contains=query) | Q(book_category__contains=query) | Q(book_number__contains=query))
	result=True
	return render_to_response('catalog/ajaxSearchPage.html',{'books':books[:20],'result':result})

@login_required(login_url="accounts:accounts-login")
def book_trans_search(request):
	query=request.GET.get('transquery',None)
	books=Book.objects.filter(Q(book_title__contains=query) | Q(book_author__contains=query) | Q(book_category__contains=query) | Q(book_number__contains=query))
	result=True
	return render_to_response('catalog/ajax_TransSearch.html',{'books':books[:20],'result':result})


def book_mtrans_search(request):
	query=request.GET.get('mquery',None)
	books=Book.objects.filter(Q(book_title__contains=query) | Q(book_author__contains=query) | Q(book_category__contains=query) | Q(book_number__contains=query))
	result=True
	return render_to_response('catalog/ajax_TransSearch.html',{'books':books[:20],'result':result})

@login_required(login_url="accounts:accounts-login")
def book_create(request):
	if(request.method=='POST'):
		bookForm=BookForm(request.POST,request.FILES)
		if(bookForm.is_valid()):
			instance.save()
			messages.success(request,f'Book added to Catalog !')
			return redirect('/core/')

		messages.success(request,f'Validation error - Explicit or invalid data format !')

	else:
		bookForm=BookForm()

	return render(request,'catalog/book_create.html',{'bookForm':bookForm})

@login_required(login_url="accounts:accounts-login")
def book_edit(request,booknumber):
	book=Book.objects.get(book_number=booknumber)
	if(request.method=='POST'):
		bookEditForm=BookForm(request.POST,request.FILES,instance=book)
		if(bookEditForm.is_valid()):
			bookEditForm.save()
			messages.success(request,f'Book updated !')
			return redirect("/core/")

		messages.success(request,f'Validation error - Explicit or invalid data format !')
		return redirect('/core/')

	else:
		editForm=BookForm(instance=book)
		return render(request,"catalog/book_edit.html",{'book':book,'editForm':editForm})

@login_required(login_url="accounts:accounts-login")
def book_delete_confirm(request,booknumber):
	if(request.method=='POST'):
		book=Book.objects.get(book_number=booknumber)
		return render(request,"catalog/book_delete_confirm.html",{'book':book})

	else:
		messages.success(request,f'Request Error - Undefined Action !')
		return redirect('/core/')

@login_required(login_url="accounts:accounts-login")
def book_delete(request,booknumber):
	if(request.method=='POST'):
		book=Book.objects.get(book_number=booknumber)
		Book.objects.get(book_number=booknumber).delete()
		messages.success(request,f'Book deleted from Catalog !')
		return redirect("/core/")
	else:
		messages.success(request,f'Request Error - Undefined Action !')
		return redirect('/core/')

catalog/templates/catalog/ajaxSearchPage.html
{% if result %}
<h3>Results</h3>
<hr>
    <div class="row">
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			<b>Book Number</b>
		</div>
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			<b>Title</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Author</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Publisher</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Category</b>
		</div>
	</div>
<hr>
{% if books %}
{% for book in books %}
	<div class="row">
		<div class="col-xl-3 col-lg-2 col-md-2 col-sm-6 col-6">
			{{book.book_number}}
		</div>
		<div class="col-xl-3 col-lg-2 col-md-2 col-sm-6 col-6">
			{{book.book_title}}
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 col-12">
			{{book.book_author}}
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 col-12">
			{{book.book_publisher}}
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-12 col-12">
			{{book.book_category}}
		</div>
		{% if book.ebook_attachments %}
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<hr>
			<a href="{{book.ebook_attachments.url}}" class="btn btn-primary btn-sm mt-1 mb-1" target="_blank">Ebook File</a>
		</div>
		{% endif %}
	</div>
	<hr>
{% endfor %}
{% else %}
	<b>No results matching query.</b>
	<br><br>
{% endif %}
{% endif %}

catalog/templates/catalog/ajax_TransSearch.html
{% if result %}
<h3>Results</h3>
<hr>
    <div class="row">
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			<b>Book Number</b>
		</div>
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			<b>Title</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Author</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Category</b>
		</div>
	</div>
<hr>
{% if books %}
{% for book in books %}
	<div class="row">
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			{{book.book_number}}
		</div>
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			{{book.book_title}}
		</div>
		<div class="col-xl-2 col-lg-3 col-md-3 col-sm-3 col-3">
			{{book.book_author}}
		</div>
		<div class="col-xl-2 col-lg-3 col-md-3 col-sm-3 col-3">
			{{book.book_category}}
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<a href="javascript:AddtoStack({{book.book_number}})" class="btn btn-info btn-sm mt-1 mb-1">Add to Queue</a>
		</div>
	</div>
	<hr>
{% endfor %}
{% else %}
	<b>No results matching query.</b>
	<br><br>
{% endif %}
{% endif %}

catalog/templates/catalog/ajax_search.html
{% if result %}
<h3>Results</h3>
<hr>
    <div class="row">
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			<b>Book Number</b>
		</div>
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			<b>Title</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Author</b>
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<b>Category</b>
		</div>
	</div>
<hr>
{% if books %}
{% for book in books %}
	<div class="row">
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			{{book.book_number}}
		</div>
		<div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-3">
			{{book.book_title}}
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			{{book.book_author}}
		</div>
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			{{book.book_category}}
		</div>
		{% if book.ebook_attachments %}
		<div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col-2">
			<hr>
			<a href="{{book.ebook_attachments.url}}" class="btn btn-primary btn-sm mt-1 mb-1" target="_blank">Ebook File</a>
		</div>
		{% endif %}
	</div>
		<hr>
		{% if user.is_staff %}
			&nbsp;<a href="{% url 'catalog:book-edit' book.book_number %}" class="btn btn-warning btn-sm mt-1 mb-1">Edit</a>
			<form class="form-group" style="float: left;" action="{% url 'catalog:book-delete-confirm' book.book_number %}" method="POST">
				{% csrf_token %}
				<input class="btn btn-danger btn-sm mt-1 mb-1" type="submit" value="Delete">
			</form>
			<hr>
			<br><br>
		{% endif %}
{% endfor %}
{% else %}
	<b>No results matching query.</b>
	<br><br>
{% endif %}
{% endif %}

catalog/templates/catalog/book_create.html
{% extends 'base.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<style>
			.card{
				height: 700px;
				overflow-y: scroll;
			}
			</style>	
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<legend>Create</legend>
							</div>
							<div class="card-body">
								<form method="POST" action="{% url 'catalog:book-create' %}" enctype="multipart/form-data">
									{% csrf_token %}
									{{bookForm|crispy}}
									<div class="form-group">
										<button class="btn btn-success" type="submit">
											Create
										</button>
									</div>
								</form>
								<a href="/core/" class="btn btn-info">Cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock %}

catalog/templates/catalog/book_delete_confirm.html
{% extends 'base.html' %}
	{% load staticfiles %}
		{% block content %}
			<style>
				.card{
					height: 700px;
					overflow-y: scroll;
				}
			</style>	
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<legend>Delete Book</legend>
							</div>
							<div class="card-body">
								<h2 class="text-justify">Are you sure you want to delete the Book - "{{book.book_title}}" by "{{book.book_author}}" ? This cannot be undone</h2>
								<hr>
								<form method="POST" action="{% url 'catalog:book-delete' book.book_number %}" class="form-group">
									{% csrf_token %}
									<input type="submit" class="btn btn-danger" value="Delete">
								</form>
								<a class="btn btn-primary" href="/core/">Cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock %}

catalog/templates/catalog/book_edit.html
{% extends 'base.html' %}
	{% load staticfiles %}
	{% load crispy_forms_tags %}
		{% block content %}

			<style>
			.card{
				height: 700px;
				overflow-y: scroll;
			}
			</style>	
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="card">
							<div class="card-header">
								<legend>Edit Book</legend>
							</div>
							<div class="card-body">
								<form method="POST" action="{% url 'catalog:book-edit' book.book_number %} " class="form-group" enctype="multipart/form-data">
									{% csrf_token %}
									{{editForm|crispy}}
									<input type="submit" class="btn btn-success" value="Update">
								</form>
								<a class="btn btn-primary" href="/core/">Cancel</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endblock %}